import fs from 'fs';
import path from 'path';
import { VrtReport } from '../core/types';

function esc(text: string): string {
  return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function imageToBase64(filePath: string): string {
  if (!fs.existsSync(filePath)) return '';
  const data = fs.readFileSync(filePath);
  return `data:image/png;base64,${data.toString('base64')}`;
}

export function generateHtmlReport(report: VrtReport, outputPath: string): void {
  const dir = path.dirname(outputPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  const rows = report.results
    .map((r) => {
      const statusColor = r.status === 'pass' ? '#3fb950' : r.status === 'new' ? '#d29922' : '#f85149';
      const baseline = imageToBase64(r.baselinePath);
      const current = imageToBase64(r.currentPath);
      const diff = r.diffPath ? imageToBase64(r.diffPath) : '';

      return `
      <div class="card">
        <div class="card-header">
          <span class="status" style="color:${statusColor}">${r.status.toUpperCase()}</span>
          <strong>${esc(r.name)}</strong>
          <span class="dim">${r.dimensions.width}x${r.dimensions.height}</span>
          ${r.status === 'fail' ? `<span class="fail-detail">${r.mismatchPercentage}% diff (${r.mismatchPixels}px)</span>` : ''}
        </div>
        <div class="images">
          ${baseline ? `<div><h4>Baseline</h4><img src="${baseline}" /></div>` : ''}
          ${current ? `<div><h4>Current</h4><img src="${current}" /></div>` : ''}
          ${diff ? `<div><h4>Diff</h4><img src="${diff}" /></div>` : ''}
        </div>
      </div>`;
    })
    .join('\n');

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Visual Regression Report</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, sans-serif; background: #0d1117; color: #c9d1d9; padding: 24px; }
  .container { max-width: 1200px; margin: 0 auto; }
  h1 { color: #f0f6fc; margin-bottom: 8px; }
  .meta { color: #8b949e; font-size: 14px; margin-bottom: 16px; }
  .summary { display: flex; gap: 16px; margin-bottom: 24px; }
  .stat { background: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 12px 20px; text-align: center; }
  .stat-value { font-size: 24px; font-weight: 700; }
  .stat-label { color: #8b949e; font-size: 12px; text-transform: uppercase; }
  .pass { color: #3fb950; } .fail { color: #f85149; } .new { color: #d29922; }
  .card { background: #161b22; border: 1px solid #30363d; border-radius: 8px; margin-bottom: 16px; overflow: hidden; }
  .card-header { padding: 12px 16px; border-bottom: 1px solid #21262d; display: flex; align-items: center; gap: 12px; }
  .status { font-weight: 700; font-size: 12px; text-transform: uppercase; }
  .dim { color: #8b949e; font-size: 13px; }
  .fail-detail { color: #f85149; font-size: 13px; }
  .images { display: flex; gap: 8px; padding: 12px; overflow-x: auto; }
  .images div { flex: 1; min-width: 0; }
  .images h4 { color: #8b949e; font-size: 11px; text-transform: uppercase; margin-bottom: 8px; }
  .images img { max-width: 100%; border: 1px solid #30363d; border-radius: 4px; }
  .footer { text-align: center; color: #484f58; font-size: 12px; margin-top: 24px; }
</style>
</head>
<body>
<div class="container">
  <h1>Visual Regression Report</h1>
  <div class="meta">${esc(report.timestamp)}</div>
  <div class="summary">
    <div class="stat"><div class="stat-value">${report.totalTests}</div><div class="stat-label">Total</div></div>
    <div class="stat"><div class="stat-value pass">${report.passed}</div><div class="stat-label">Passed</div></div>
    <div class="stat"><div class="stat-value fail">${report.failed}</div><div class="stat-label">Failed</div></div>
    <div class="stat"><div class="stat-value new">${report.newBaselines}</div><div class="stat-label">New</div></div>
  </div>
  ${rows}
  <div class="footer">Generated by visual-regression-toolkit</div>
</div>
</body>
</html>`;

  fs.writeFileSync(outputPath, html, 'utf-8');
}
